name: Run tests

on: [push]

jobs:
  build:
    runs-one: ubuntu-latest

    steps:
    - uses: action/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-verion: "3.11"

    - name: Install pipenv
      run: |
        pip install pipenv

    - name: Install dependencies
      run: |
        pipenv install

    - name: Run test
      run: |
        pipenv run python config/manage.py test

